# Generate coverage in JSON format.
#
# This target uses [Istanbul](https://github.com/gotwarlost/istanbul) to
# transparently instrument a [Vows](http://vowsjs.org/) test suite and collect
# code coverage statistics.
#
# The JSON object generated by Istanbul has the following format:
#
#     {
#          "/path/to/file1.js": { file1 coverage },
#          "/path/to/file2.js": { file2 coverage }
#     }
#
# The internals of the file coverage object are [intentionally not documented][1]
# since it is not a public interface.
$(checkstatedir)/cov/coverage.json: $(SOURCES) $(TESTS)
	$(ISTANBUL) cover $(ISTANBULFLAGS) --report=none --dir $(checkstatedir)/cov $(shell which vows) -- $(VOWSFLAGS) $(TESTS)
